### ISSUE TITLE
asus-armoury module not working

### ISSUE THREAD

**Issue by Emiliopg91** [CachyOS/kernel-patches#122]
Hi, I've faced the following issue:

- **Hardware**: Asus ROG Xbox Ally X
- **Kernel**: 6.17.6-2-cachyos-deckify #1 SMP PREEMPT_DYNAMIC Fri, 31 Oct 2025 15:34:17 +0000 x86_64 GNU/Linux
- **chwd**:  chwd-1.16.0-2 provided by  @1Naim via Discord
- **input-plumber**: 0.67.0-1.1
- **cachyos-bugreport.sh**: [https://paste.cachyos.org/p/c5dd557.log](https://paste.cachyos.org/p/c5dd557.log)
- **Result**: asus-armoury not loading
- **Expected**: module loading and exposing TDP firmware-attributes 

Every button of the handheld PC works flawlessly.
However TDP slider doesn't show up in UI and setting TDP using SimpleDeckyTDP or my own plugin (AllyDeckyCompanion) that works on Bazzite (for 2024 Asus Rog Ally X, the plugin works in bazzite and cachyos) TDP isn't working at all

I've realized that asus-armoury driver performs checks on load that doesn't ends up properly showing following output in logs:

```bash
[10621.578901] asus_armoury: Invalid CPU cores count detected: interface is not safe to be used.
[10621.578910] asus_armoury: Could not initialise CPU core control: -22
```

The guilty method is this one:

```C
static struct cpu_cores *init_cpu_cores_ctrl(void)
{
	u32 cores;
	int err;
	struct cpu_cores *cores_p __free(kfree) = NULL;

	cores_p = kzalloc(sizeof(struct cpu_cores), GFP_KERNEL);
	if (!cores_p)
		return ERR_PTR(-ENOMEM);

	err = armoury_get_devstate(NULL, &cores, ASUS_WMI_DEVID_CORES_MAX);
	if (err) {
		pr_err("ACPI does not support CPU core count control\n");
		return ERR_PTR(-ENODEV);
	}

	cores_p->max_power_cores = FIELD_GET(ASUS_POWER_CORE_MASK, cores);
	cores_p->max_perf_cores = FIELD_GET(ASUS_PERF_CORE_MASK, cores);

	err = armoury_get_devstate(NULL, &cores, ASUS_WMI_DEVID_CORES);
	if (err) {
		pr_err("Could not get CPU core count: error %d\n", err);
		return ERR_PTR(-EIO);
	}

	cores_p->cur_power_cores = FIELD_GET(ASUS_POWER_CORE_MASK, cores);
	cores_p->cur_perf_cores = FIELD_GET(ASUS_PERF_CORE_MASK, cores);

	cores_p->min_power_cores = CPU_POWR_CORE_COUNT_MIN;
	cores_p->min_perf_cores = CPU_PERF_CORE_COUNT_MIN;

	if ((cores_p->min_perf_cores > cores_p->max_perf_cores) ||
	    (cores_p->min_power_cores > cores_p->max_power_cores) ||
		(cores_p->cur_perf_cores > cores_p->max_perf_cores) ||
		(cores_p->cur_power_cores > cores_p->max_power_cores) ||
		(cores_p->cur_perf_cores < cores_p->min_perf_cores) ||
		(cores_p->cur_power_cores < cores_p->min_power_cores)
	) {
		pr_err("Invalid CPU cores count detected: interface is not safe to be used.\n");
		return ERR_PTR(-EINVAL);
	}
```

**Comment by Emiliopg91** [comment]
If I can help with testing you can count on me
I dont have experience in kernel related things but I'm developer with experience in Linux and I have the "problematic" hardware... And... I'm willing to learn new things :)

**Comment by Emiliopg91** [comment]
Solved in 6.18-rc6
I'll wait for 6.18 release being in RC

any bug I'll report it

**Comment by 1Naim** [comment]
> why do you expect to have it ready for 6.17.9?

Because it's already queued in tree and the upcoming kernel version is 6.17.9



> Will be added the fix/firmware for Xbox Ally X speakers to solve the issue with volume?

Eventually. AFAIK there's still an issue that's still unresolved.

> what about the chwd for Xbox ally x?

Already merged upstream, wait for a new point release.
